### ISSUE TITLE
svg elements get recreated rather than patched?

### ISSUE THREAD

**Issue by sunwukung** [Matt-Esch/virtual-dom#159]
I'm experimenting with the svg component - but it seems the svg element is getting multiple writes of the same nodes, rather than patching the changes?  
 
	  var update = function (state, oldTree, rootNode) {
	       var newTree = polygonSVG(state),
	            patches = diff(oldTree, newTree);
	       rootNode = patch(rootNode, patches);
	   };

	  var tree = polygonSVG({
	      points: points,
	      cursor: {
	        x: 0,
	        y: 0
	      }
	    })
	    , rootNode = createElement(tree)
	    , moveStream = domStreams.mousemove(rootNode)
	    , clickStream = domStreams.click(rootNode)
	    , clickHandler = (e) => {
	      var mPos = getMousePosition(e);
	      points.push(mPos);
	      update({
	          points: points,
	          cursor: mPos
	        },
	        tree,
	        rootNode
	      );
	    }
	    , moveHandler = (e) => {
	        update({
	          points: points,
	          cursor: getMousePosition(e)
	        },
	        tree,
	        rootNode
	      );
	    };

	  clickStream.onValue(clickHandler);
	  moveStream.onValue(moveHandler);
	
	  document.querySelector("#app-container").appendChild(rootNode);

    // polygonSVG
	export default function (state) {
	  var lastPoint = getLastPoint(state.points)
	    , circles = state.points.map((val, i, arr) => {
	      return svg("circle", {
	        cx: val.x,
	        cy: val.y,
	        r: 10
	      });
	    })
	    , lines = state.points.map((val, i, arr) => {
	      var endPos = (i === arr.length - 1)
	        ? arr[i]
	        : arr[i + 1];
	      return svg("line", {
	        x1: val.x,
	        y1: val.y,
	        x2: endPos.x,
	        y2: endPos.y,
	        stroke: "red",
	        "stroke-width": 2
	      });
	    })
	    , cursorLine = svg("line", {
	      x1: lastPoint.x,
	      y1: lastPoint.y,
	      x2: state.cursor.x,
	      y2: state.cursor.y,
	      stroke: "blue",
	      "stroke-width": 2
	    })
	    , childElements = lines.concat(circles);
	
	
	  return h("div",
	      {
	        id: "svg-container"
	      },
	      [
	      svg("svg", {
	          id: "svg-polygon",
	          width: 640,
	          height: 640
	      }, childElements),
	      svg("svg", {
	        id: "svg-cursor",
	        width: 640,
	        height: 640
	        }, [cursorLine])
	      ]
	    );
	};
  
I had to put the cursor on a separate svg element, as it was also drawing the same line multiple times. Do I need to give these elements some sort of identifier to help with patching the tree, or does patch ignore svg? Or have I just got something wrong.

**Comment by Matt-Esch** [comment]
The child nodes are matched one to one, so suppose you had previous child nodes `[1, 2, 3]`, and new child nodes `[1, 2, 3]`, the diff algorithm will diff(1, 1), diff(2, 2) and diff(3, 3). If the nodes are no longer the same type (tagName, widget, thunk type), the node will be replaced.

However you do sometimes want to preserve a previous node when it is out of order. If you want to preserve a previous node you can do so by adding a key property. This will re-order the nodes prior to diffing to ensure that any previous nodes with keys match any new nodes with the same key.

```js
function specialCircle(cx, cy, r) {
    return svg('circle', {
        key: 'special-circle',
        cx: cx,
        cy: cy,
        r: r
    });
}
```

So here if you diff `[a, b, specialCircle]` and `[specialCircle, a, b]`, because `specialCircle` has a key, the `specialCircle` will be moved from the end to the start and any property patches applied.

Note that:

- keys must be unique in any collection of child nodes.
- reordering can be expensive so you should try to avoid keys where possible

**Comment by sunwukung** [comment]
I found the problem - I'm not reassigning the tree after calling update:

    var update = function (state, oldTree, rootNode) {
           var newTree = polygonSVG(state),
                patches = diff(oldTree, newTree);
           rootNode = patch(rootNode, patches);
           // need to send this back
           return newTree;
       };

    clickHandler = (e) => {
          var mPos = getMousePosition(e);
          points.push(mPos);
          // this is the missing part!
          tree = update({
              points: points,
              cursor: mPos
            },
            tree,
            rootNode
          );
        }
