### ISSUE TITLE
VNode should follow hyperscript's standard tagName

### ISSUE THREAD

**Issue by bitinn** [Matt-Esch/virtual-dom#160]
While checking out both `virtual-dom-stringify` and `vdom-to-html` I am seeing all uppercase tagName output, but for some reasons their tests aren't broken.

So I dig further and found this:

```
var n1 = new VNode('span');
var n2 = new VNode('SPAN');
n1.tagName === n2.tagName // false
```

```
var n1 = h('span');
var n2 = h('SPAN');
n1.tagName === n2.tagName // true
```

both module only tests for `VNode`, not `h`, so this issue is hidden from tests.

so #140 needs further work.

**Comment by Matt-Esch** [comment]
It's intentional that case conversion happens in virtual-hyperscript and not in the VNode constructor. This is so that people who are using the correct case in their code by convention do not have to suffer the performance overhead of case converting the tags. The virtual node has no opinion about case and defaults to leaving it as it is set.

**Comment by bitinn** [comment]
I understand if that's the decision, though I am not sure how to feel about this:

```
var n1 = new VNode('span');
var n2 = h('span');
n1.tagName === n2.tagName // false
```

Both `virtual-dom-stringify` and `vdom-to-html` now fixed this issue by running `toLowerCase()` on all VNode, because one doesn't know if a VNode is created by calling `new VNode` or via `h`, and presumably people like tags to be lowercase on output.

PS: would also like to know the correct case for VNode, upper or lower?

**Comment by staltz** [comment]
`var n1 = new VNode('span');`

tag names should be uppercase according to the DOM spec, so with this line of code you are going against the correct output format. VNode constructor is a low-level tool, so you need to uppercase tagnames manually.

`var n2 = h('span');`

In this line you are letting virtual-hyperscript take care of the uppercasing for you. People like to type in lowercase, but it still isn't following the specs.

`n1.tagName === n2.tagName // false`

Why is this a problem? (Consider the first paragraph above)

**Comment by bitinn** [comment]
Just need to make sure in both case uppercase is the *correct* case (even though VNode doesn't care, and hyperscript does auto-convert), because currently all documents use lower-case and browsers have spoil us by making sure tagName are consistent.

**Comment by neonstalwart** [comment]
VNode also has potential to be used in not-the-DOM so it's reasonable for it not to enforce DOM conventions.

**Comment by bitinn** [comment]
IMHO:

Perhaps VNode is such a low-level tool that performance is crucial and `toLowerCase()` has a meaningful impact on speed. But I am not so certain without benchmarking.

```
var i = 0;
var t = 'span';
console.log(performance.now(), t, i);
while(i < 100000) { t = t.toUpperCase(); t = t.toLowerCase(); i++; }
console.log(performance.now(), t, i);
//2015-01-09 14:22:38.707VM417:4 270619.86100000015 "span" 0
//2015-01-09 14:22:38.871VM417:6 270783.94200000004 "span" 100000

var i = 0;
var t = 'span';
console.log(performance.now(), t, i);
while(i < 100000) { i++; }
console.log(performance.now(), t, i);
//2015-01-09 14:24:13.885VM426:4 365802.2920000003 "span" 0
//2015-01-09 14:24:13.954VM426:6 365871.25800000015 "span" 100000

// so it's about 100ms in 100,000 calls
// in contrast, yahoo.com has about ~1800 nodes on load, and goes up to ~5900 nodes if we scroll to the end.
```

Maybe there are developers relying on VNode to be case-sensitive, but by looking at `virtual-dom-stringify` and `vdom-to-html` before 1.0 patch, they both assume people will use `new VNode('span')`not `new VNode('SPAN')` (and implicitly, `h('span')` instead of `h('SPAN')`), while latter is the *correct* case.

So while I agree there isn't a strong need to change VNode behaviour, I also don't see a need for VNode to diverge from DOM standard.

**Comment by neonstalwart** [comment]
> So while I agree there isn't a strong need to change VNode behaviour, I also don't see a need for VNode to diverge from DOM standard.

VNode is not just about DOM nodes.  it's a generic node in a tree diff algorithm.  what the node represents is outside of the concern of VNode and the diff algorithm so doing something like adjusting the case of the `tagName` would be a bad idea to do inside of VNode regardless of how it performs.

`h` is part of a toolchain that generates DOM nodes using a VNode tree.  this is why it makes sense for `h` to do the capitalization - it is aware of the domain it is being applied to whereas VNode is not.  does that make sense?

**Comment by bitinn** [comment]
@neonstalwart I agree with you on that.

Though I think people (ie. me) assume `h()` is just a shorter version of `new VNode()`, while it isn't; VNode is a very low-level tool and if you are doing anything DOM-related, `h()` is almost guaranteed to be the better/safer choice. While both return a VNode instance, `h` does a lot more work to ensure valid DOM output.

Yet many modules are tested based on `VNode`, not `h`. This results in module breaking during recent `virtual-dom` 1.0 bump: because VNode doesn't really care about DOM, so testcases passes; while user using `h` to generate DOM will notice the issue.

Maybe the alternative is to provide clearer document on the [DOM model section](https://github.com/Matt-Esch/virtual-dom#dom-model), because it gives me impressions that those are equivalent, while they are very much not.

**Comment by bitinn** [comment]
@TimBeyer my experience is that: for browsers it doesn't matter as they are handled by DOM API, but for node.js it require module to handle any work that `h` will do but `VNode` doesn't.

**Comment by neonstalwart** [comment]
> Yet many modules are tested based on VNode, not h. This results in module breaking during recent virtual-dom 1.0 bump: because VNode doesn't really care about DOM, so testcases passes; while user using h to generate DOM will notice the issue.

fair point.  i think virtual-dom shoulders some of the blame here due to some code organization changes that weren't pinned down until close to the 1.0 tag (i.e. `h` was likely not even part of this repo when those other libs built on virtual-dom) but ultimately those other projects are where the most change needs to happen now that virtual-dom has settled.

one of the things which held back a 1.0 tag was the lack of docs and so it's understood that docs are important and can always be improved.  any PRs to improve docs are very welcome.

**Comment by staltz** [comment]
>Yet many modules are tested based on VNode, not h. This results in module breaking during recent virtual-dom 1.0 bump: because VNode doesn't really care about DOM, so testcases passes; while user using h to generate DOM will notice the issue.

Easy problem. virtual-dom-stringify and html-to-vdom and others should update themselves with virtual-dom 1.0 that doesn't have the assumption that VNode converts to uppercase (or that virtual hyperscript doesn't output lowercase).

**Comment by TimBeyer** [comment]
@staltz Imho libraries working with virtual-dom should not have it as a direct dependency at all, but use explicit dependency injection. html-to-vdom handles it that way. Otherwise you cannot know how your and your users' versions interact.

**Comment by staltz** [comment]
But virtual-dom pre-1.0 was work-in-progress, so no point supporting it.

**Comment by Matt-Esch** [comment]
We can think of a VNode as an XML node. XML tag names are case sensitive. The default namespace in the DOM expects nodes to be case insensitive and for DOM implementations to do the correct case conversion. DOM nodes under a name space do have case sensitivity on their tag names.

If I'm honest, I would have preferred to default to lower case in virtual-hyperscript, since this is what most people lean towards when they are creating nodes. The fact that virtual-hyperscript coerces to upper case in a world where everyone us using lower case is really the reason why this problem has been highlighted. It's only upper case because reading tag names out of the DOM will give you upper case names, and I think there is some value in having parity between these two.
