### ISSUE TITLE
Why are hooks being executed on empty diffs?

### ISSUE THREAD

**Issue by smelnikov** [Matt-Esch/virtual-dom#188]
It seems that whenever I use a hook and then do a diff between two identical trees, it will generate a diff that includes all the nodes that have the hooks on them with no other value than the hook itself. It will then proceed to call all the hooks. 

This seems like wasted computation at best, since if there are no changes to patch why would the hooks be called?

Perhaps `diffProps` should only add hooks if there is at least one other property that has changed? I can create a PR if this is the agreed upon route.

**Comment by Raynos** [comment]
@smelnikov This should not be the case.

Hooks should be soft hooks if the trees are identical, i.e. the exact same thing `tree1 === tree2`.

If they are structurally deep equal then they are not the same and we will do a deep diff and fire all the hooks.

Hooks are stateful entities, if they are different, i.e. `leftHook !== rightHook` then we fire the hook even if the two hooks are deep equal. This is because the hook method might be a closure.

**Comment by smelnikov** [comment]
Perhaps I'm mis-using hooks or do not fully understand their purpose. I thought they were for calling a method when an element has changed as a result of a patch or a create. So my confusion comes from trying to understand why they're being called when a patch results with no changes to the DOM. (structurally deep equal trees).

I also made the mistake of using a new instance of a hook for every diff. oops.

**Comment by smelnikov** [comment]
After reading the mercury docs on hooks I have a slightly better idea. 

Should those docs be moved/copied to virtual-dom? There seems to be no mention of hooks in the documentation of this project.

**Comment by Raynos** [comment]
@smelnikov there is an open PR for hook documentation :)
