### ISSUE TITLE
Am I missing something?

### ISSUE THREAD

**Issue by radutopala** [Matt-Esch/virtual-dom#205]
Hi guys,

I've been trying `virtual-dom`, sample here: https://gist.github.com/radutopala/fe57d5da66c8be3326b9

I'm basically trying to compute diffs between 2 web pages. But the diff doesn't work as expected when running this script in node, meaning that I don't see any `VirtualPatch` objects in `console.log`. Am I missing something?

**Comment by neonstalwart** [comment]
there's a typo... https://gist.github.com/radutopala/fe57d5da66c8be3326b9#file-vdom-diff-js-L6  `oltTree` instead of `oldTree` - maybe that's it?

**Comment by radutopala** [comment]
@neonstalwart fixed that, still no luck with the script. Maybe `virtual-dom` is meant to do diffs only in browser..?

**Comment by algesten** [comment]
I run it successfully using jsdom in the test cases for [trifl](https://github.com/algesten/trifl) (check out the test/global.coffee). The problem is that virtual-dom relies on [global](https://github.com/Raynos/global) which, in case no DOM implementation is detected, polyfills with [min-document](https://github.com/Raynos/min-document).

Min-document is way too minimal for what I tried to do, so I couldn't use this out of the box.

**Comment by radutopala** [comment]
@algesten you've done interesting things with `trifl` :) thanks for sharing

**Comment by neonstalwart** [comment]
@radutopala your problem is that html2hscript does not do what you think it does.  take a look at its [test](https://github.com/twilson63/html2hscript/blob/7334f7e32ee90a0a62de8f512a3ece65205462d8/test/index_test.js#L4-L9).  it parses a string like `'<h1 foo="beep">Hello World</h1>'` into another string like `'h("h1", { "foo": "beep"}, [ "Hello World" ])'`.

you are then trying to do a diff of `'h("h1", { "foo": "beep"}, [ "Hello World" ])'` which is meaningless.  instead, you want to turn something like `'<h1 foo="beep">Hello World</h1>'` into virtula-dom nodes.  if you were to execute the **code** (not just a string) created by the parser:

```js
var newTree = h("h1", { "foo": "beep"}, [ "Hello World" ])
```

then do a diff of that, it would be what you're wanting.

there are libraries which will automatically parse html into a vdom tree for you so that you don't need to parse html to code and then execute the code.  see the [wiki](https://github.com/Matt-Esch/virtual-dom/wiki#html-to-vdom) for a list of libraries you could use instead of html2hscript

**Comment by radutopala** [comment]
@neonstalwart yeah, figure it out already with the string output, thanks! closing the ticket.
