### ISSUE TITLE
Question about vnode.key

### ISSUE THREAD

**Issue by kuraga** [Matt-Esch/virtual-dom#234]
Good day!

We have in `VNode`'s docs:
```
key (optional)
An identifying string used to differentiate this node from others. Used internally by vtree/diff to do node reordering.
```

What does it mean for me? Is this meaning mentioned in docs?

**Comment by neonstalwart** [comment]
it means that if you have a node that can be uniquely identified (uniqueness only needs to be local - i.e. unique among its siblings, but not necessarily globally unique) and it is part of a list of items which you may want to reorder then if you set the `key` to that unique identifier, the diff can optimize reordering so that sibling nodes are shuffled in the DOM rather than trying to leave nodes where they are and putting new data into them.

**Comment by kuraga** [comment]
So, without keys, order of DOM elements is (garanteed) the same as arguments order? And I have to use `key` *only if I want to reorder them*?

**Comment by neonstalwart** [comment]
i don't know exactly what you mean - but, yes, keys are only for efficient reordering.  if you don't reorder, don't use keys.

if you initially have nodes in this order... `[ a, b, c ]` and then you reorder them to be `[ b, c, a ]`.

if you use keys then the patches generated will say to reorder the nodes 
* move nodes[0] to nodes[2]

if you don't use keys then the patches will say:
* update nodes[0] to look like the new b node, 
* update nodes[1] to look like the new c node, 
* update nodes[2] to look like the new a node  

do you see the difference?

**Comment by kuraga** [comment]
Thanks! Yes, I see.

I just wanted to clarify that order of nodes without keys is defined (and is not undefined).
