### ISSUE TITLE
No for possible on a label element?

### ISSUE THREAD

**Issue by batiste** [Matt-Esch/virtual-dom#278]
virtualDom.create(virtualDom.h('label', {for:1, title:2}))
    <label title="2"></label>

Why does the "for" attribute doesn't work?

**Comment by andrewrota** [comment]
The property name for the attribute `for` is `htmlFor` [[1]](https://developer.mozilla.org/en-US/docs/Web/API/HTMLLabelElement).  Changing `for:1` to `htmlFor: 1` should work.

**Comment by batiste** [comment]
Do you have a list of those properties like class -> className, for -> htmlFor ?

I imagine it is something inherent to the DOM model somehow...

**Comment by andrewrota** [comment]
We have an [attribute:property mapping](https://github.com/wayfair/tungstenjs/blob/42535b17e4894e866abf5711be2266458bc4d508/src/template/template_to_vdom.js#L118-L140) on a project that uses virtual-dom because we convert templates to vdom objects and we know everything is getting passed in as an attribute.

You can also pass in attributes directly to virtual-dom by using the `attributes` property.  So your example could also look like this and work:

    virtualDom.create(virtualDom.h('label', {attributes:{for: 1}, title:2}))

**Comment by Matt-Esch** [comment]
virtual-dom doesn't try to have an .needsopinion about this. We just give you a way to set properties and attributes on nodes

**Comment by feross** [comment]
To anyone finding this in the future... I just published a package [`hyperscript-attribute-to-property`](https://www.npmjs.com/package/hyperscript-attribute-to-property) to solve this issue.

With this package, you can do this:

```js
var vnode = h('div', { class: 'my-class' })
```

Instead of this:

```js
var vnode = h('div', { className: 'my-class' })
```

Works with `for` and the others, too :)
