### ISSUE TITLE
Virtual DOM for React

### ISSUE THREAD

**Issue by gyzerok** [Matt-Esch/virtual-dom#282]
According to [React 0.14 beta](http://facebook.github.io/react/blog/2015/07/03/react-v0.14-beta-1.html) its now possible to use custom VDOM implementation with React.
As I know [virtual-dom](https://github.com/Matt-Esch/virtual-dom) is the fastest implementation of VDOM idea for now. So I'm requesting an implementation for React.

**Comment by staltz** [comment]
I don't think you understood why they split it. The idea isn't the swap the implementation of the virtual DOM, the idea is to allow other implementations of virtual _whatever_. For targetting the DOM, it's pretty clear React will keep react-dom.

Notice
>The react package contains React.createElement, React.createClass and React.Component, React.PropTypes, React.Children, and the other helpers related to elements and component classes. We think of these as the isomorphic or universal helpers that you need to build components.

`virtual-dom` has it's own concepts to replace React.createElement, Reacte.createClass, React.Component, so they are kind of incompatible.

**Comment by stevenvachon** [comment]
[cito.js](https://github.com/joelrich/citojs) is faster in almost every benchmark test.

**Comment by Matt-Esch** [comment]
Yeah I don't think React can be modularized in the way that we would like, that's why this project exist.

I think most virtual DOM implementations written after react are an order of magnitude more efficient, with varying degrees of trade off. virtual-dom's biggest weakness right now is the DOM lookup code that walks the DOM looking for the nodes we want to patch. Caching the DOM in a js tree structure would probably increase perf significantly. Also as we start dealing with a lot of real world problems `h` becomes more expensive for convenience.

I would love React to be pluggable, but it's just not designed like that and probably won't ever be.

**Comment by christianramsey** [comment]
@staltz Why they split it isn't as important as what possibilities it opens up for developers/designers who use react. They will ultimately decide what the split means for them and how they will take advantage of this decoupling.

@staltz  The article also says: 

>To start, we expect people to render DOM-based components with our react-dom package, but there's >nothing stopping someone from diving deep on performance and writing a awesome-faster-react-dom >package which can render the exact same DOM-based components. By decoupling the component >definitions from the rendering, this becomes possible.
>[React Blog Article](https://facebook.github.io/react/blog/2015/07/03/react-v0.14-beta-1.html)

Let's focus on the key differences:
- Dom Abstraction (unsure)
- Speed (v-dom)
- Component Creation (react)

Virtual-Dom may be "the winner" when it comes to speed but React's way of creating components is definitely preferable by much of the community. Rather intentional or not, this has drastically changed the way components are created, choosing either library means you are also adopting or at the very least it influences the way you define and structure your components. This is a hurdle to adoption for those who dislike/hate/disagree with Virtual-Dom's way of doing this.

If it is in fact possible to create a faster replacement for react-dom (as the React team have said it very well could be), why couldn't we take the learnings of the Virtual-Dom library and apply them in a decoupled way to react as a react-dom replacement (i.e. react-vdom)? 

@Matt-Esch Though it may not be optimal in the way that we "envision" or model mentally, I don't think a pluggable react is hopeless consider their current direction. I can't imagine why this wouldn't be possible now or in future versions of React. 

@gyzerok 
I'm looking forward to seeing what this decoupling will inspire and think this should be reopened as more people try the beta and grok the possible implications.

![screenshot 2015-07-12 10 51 30](https://cloud.githubusercontent.com/assets/1045587/8638276/252ba224-2884-11e5-8220-aa8923f001a8.jpg)
